
services:
  kalshi-dashboard:           # Name of your service
    build: .                  # Use Dockerfile in current directory
    image: kalshi-dashboard:data-fetcher-orderbook   # Specify image name and tag
    ports:
      - "8080:8080"           # Map port 8080 from container to host
    volumes:
      - ./src:/app/src        # Mount src directory into the container
      - ~/.kalshi_keys:/app/keys:ro  # Mount keys directory as read-only
      - ./market_data:/app/market_data  # Mount market_data directory
    environment:
      - PROD_KEYFILE=/app/keys/kalshi_prod_key.pem
      - PROD_KEYID=${PROD_KEYID}
      - DEMO_KEYFILE=/app/keys/kalshi_demo_key.pem
      - DEMO_KEYID=${DEMO_KEYID}
      - LOCAL_MODE=${LOCAL_MODE}
      - COMPOSE_BAKE=${COMPOSE_BAKE}
